# Site settings
title: Dotloom Project
description: Next Generation Point Cloud Platform
author: Dotloom Project

# Page Information
about:
  Dotloom is an open source platform for working with very large point cloud
  datasets.  From data collection from remote sensors to consumer ready data
  products, Dotloom strives to make every step of working with point cloud
  data as secure, simple, and efficient as possible. Dotloom is built with
  speed, security, and efficiency in mind.
github_username: dotloom

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
